# Generated by Django 3.2 on 2021-04-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('km', models.PositiveIntegerField()),
                ('moteur', models.FloatField()),
                ('transmission', models.CharField(max_length=10)),
                ('carburant', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('searched_counter', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.category')),
            ],
        ),
    ]
