# Generated by Django 3.2 on 2021-04-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicule',
        ),
    ]
