# Generated by Django 3.2 on 2021-04-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20210421_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='transmission',
        ),
    ]
