# Generated by Django 3.2 on 2021-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20210421_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(default='marque', max_length=255)),
                ('modele', models.CharField(default='modele', max_length=255)),
                ('price_km_supp', models.FloatField()),
                ('price_rayure', models.FloatField()),
            ],
        ),
    ]
