# Generated by Django 3.2 on 2021-04-21 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_pricinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(default='marque', max_length=255)),
                ('modele', models.CharField(default='modele', max_length=255)),
                ('price_km_supp', models.FloatField()),
                ('price_rayure', models.FloatField()),
                ('date_modification', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='pricinginfo',
            name='date_modification',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 6, 43, 966140, tzinfo=utc)),
        ),
    ]
