# Generated by Django 3.2 on 2021-04-21 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20210421_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='initial_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='date_modification',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 19, 2, 32, 361700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='moteur',
            field=models.FloatField(default=0),
        ),
    ]
